# .github/workflows/ci.yml

name: Run ChIP-Seq CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/

    - name: Install nf-test
      run: |
        pip install nf-test

    - name: Build Docker image
      run: docker build -t chipseq-pipeline .

    - name: Run nf-test
      run: nf-test test
