name: CI/CD Pipeline for Nextflow Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t nextflow-analysis .

      - name: Run Nextflow pipeline
        run: |
          docker run --rm -v $(pwd):/mnt nextflow-analysis run /mnt/main.nf
